// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Deals = sequelize.define('deals', {
    origoEnergy: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    signatureDate: {
      type: DataTypes.DATEONLY,
    },
    cancellation: {
      type: DataTypes.DATEONLY,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    managerId: {
      type: DataTypes.INTEGER,
    },
    entityId: {
      type: DataTypes.BIGINT,
    },
    archived: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    archivedAt: {
      type: DataTypes.DATE,
    },
    prePaid: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
  }, {
    tableName: 'deals',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Deals.associate = (models) => {
    Deals.belongsTo(models.adminUsers, {
      foreignKey: 'manager_id',
      as: 'manager'
    });
    Deals.belongsTo(models.entities, {
      foreignKey: 'entity_id',
      as: 'entity'
    });
    Deals.hasMany(models.products, {
      as: 'products'
    });
    Deals.hasMany(models.activeAdminComments);
  };

  return Deals;
};
